/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2023-08-18 03:34:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.back_002dend.emp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.emp.model.*;

public final class listAllEmp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1649830021382L));
    _jspx_dependants.put("jar:file:/C:/CHA102_WebApp/eclipse_WTP_workspace4B_To-SpringBootMVC_1-5-8U/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/0201U_Servlet_JSP_Ver2_DB/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1064305020000L));
    _jspx_dependants.put("/back-end/emp/included-fragment.file", Long.valueOf(1651025550912L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.emp.model");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
  
    EmpService empSvc = new EmpService();
    List<EmpVO> list = empSvc.getAll(); 
    if(request.getAttribute("empListData")==null) pageContext.setAttribute("empListData",list);

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<title>所有員工資料 - listAllEmp.jsp</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/webjars/bootstrap/4.2.1/css/bootstrap.min.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/index.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/error.css\"/>");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.js\"></script>                                    <!-- ●●js  for jquery datatables 用 -->\r\n");
      out.write("<script	src=\"https://cdn.datatables.net/1.13.5/js/jquery.dataTables.min.js\"></script>              <!-- ●●js  for jquery datatables 用 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.datatables.net/1.13.5/css/dataTables.jqueryui.min.css\" /> <!-- ●●css for jquery datatables 用 -->\r\n");
      out.write("\r\n");
      out.write("<!-- ●● jquery datatables 設定 -->\r\n");
      out.write("<script>\r\n");
      out.write("	$(document).ready(function() {\r\n");
      out.write("		$('#example').DataTable({\r\n");
      out.write("			\"lengthMenu\": [3 ,5, 10, 20, 50, 100],\r\n");
      out.write("			\"searching\": true,  //搜尋功能, 預設是開啟\r\n");
      out.write("		    \"paging\": true,     //分頁功能, 預設是開啟\r\n");
      out.write("		    \"ordering\": true,   //排序功能, 預設是開啟\r\n");
      out.write("		    \"language\": {\r\n");
      out.write("		        \"processing\": \"處理中...\",\r\n");
      out.write("		        \"loadingRecords\": \"載入中...\",\r\n");
      out.write("		        \"lengthMenu\": \"顯示 _MENU_ 筆結果\",\r\n");
      out.write("		        \"zeroRecords\": \"沒有符合的結果\",\r\n");
      out.write("		        \"info\": \"顯示第 _START_ 至 _END_ 筆結果，共<font color=red> _TOTAL_ </font>筆\",\r\n");
      out.write("		        \"infoEmpty\": \"顯示第 0 至 0 筆結果，共 0 筆\",\r\n");
      out.write("		        \"infoFiltered\": \"(從 _MAX_ 筆結果中過濾)\",\r\n");
      out.write("		        \"infoPostFix\": \"\",\r\n");
      out.write("		        \"search\": \"搜尋:\",\r\n");
      out.write("		        \"paginate\": {\r\n");
      out.write("		            \"first\": \"第一頁\",\r\n");
      out.write("		            \"previous\": \"上一頁\",\r\n");
      out.write("		            \"next\": \"下一頁\",\r\n");
      out.write("		            \"last\": \"最後一頁\"\r\n");
      out.write("		        },\r\n");
      out.write("		        \"aria\": {\r\n");
      out.write("		            \"sortAscending\":  \": 升冪排列\",\r\n");
      out.write("		            \"sortDescending\": \": 降冪排列\"\r\n");
      out.write("		        }\r\n");
      out.write("		    }\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body {\r\n");
      out.write("	margin: 1rem 12rem 2rem 12rem;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-md navbar-dark bg-success fixed-top justify-content-center\">\r\n");
      out.write("		 <div align=\"center\"> <h2>所有員工資料 - listAllEmp.jsp</h2>\r\n");
      out.write("		 <h3><a class=\"navbar-brand\" href=\"");
      out.print(request.getContextPath());
      out.write("/back-end/emp/select_page.jsp\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/images/back1.gif\">回查詢頁");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${success}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a></h3></div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<table id=\"example\" class=\"display\" style=\"width: 100%\">\r\n");
      out.write("  <thead >\r\n");
      out.write("	<tr style=\"background-color:#CCCCFF\">\r\n");
      out.write("	    <th>計數</th>\r\n");
      out.write("		<th>員工編號</th>\r\n");
      out.write("		<th>員工姓名</th>\r\n");
      out.write("		<th>職位</th>\r\n");
      out.write("		<th>雇用日期</th>\r\n");
      out.write("		<th>薪水</th>\r\n");
      out.write("		<th>獎金</th>\r\n");
      out.write("		<th>照片</th>\r\n");
      out.write("		<th>部門</th>\r\n");
      out.write("		<th>修改</th>\r\n");
      out.write("		<th>刪除</th>\r\n");
      out.write("	</tr>\r\n");
      out.write("  </thead>\r\n");
      out.write("\r\n");
      out.write(" <tbody>\r\n");
      out.write("	");
      //  c:forEach
      org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
      boolean _jspx_th_c_005fforEach_005f0_reused = false;
      try {
        _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fforEach_005f0.setParent(null);
        // /back-end/emp/listAllEmp.jsp(85,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f0.setVar("empVO");
        // /back-end/emp/listAllEmp.jsp(85,1) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empListData}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        // /back-end/emp/listAllEmp.jsp(85,1) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f0.setVarStatus("s");
        int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
        try {
          int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
          if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write("\r\n");
              out.write("		<tr>\r\n");
              out.write("            <td>");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("</td>\r\n");
              out.write("			<td>");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empVO.empno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("</td>\r\n");
              out.write("			<td>");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empVO.ename}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("</td>\r\n");
              out.write("			<td>");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empVO.job}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("</td>\r\n");
              out.write("			<td>");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empVO.hiredate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("</td>\r\n");
              out.write("			<td>");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empVO.sal}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("</td>\r\n");
              out.write("			<td>");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empVO.comm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("</td> \r\n");
              out.write("			<td><img src=\"");
              out.print(request.getContextPath());
              out.write("/emp/DBGifReader?empno=");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empVO.empno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("\" width=\"100px\"></td> \r\n");
              out.write("			<td>");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empVO.deptno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write('-');
              out.write('[');
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empVO.deptVO.dname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("]</td>\r\n");
              out.write("			<td>\r\n");
              out.write("			  <FORM METHOD=\"post\" ACTION=\"");
              out.print(request.getContextPath());
              out.write("/emp/emp.do\" style=\"margin-bottom: 0px;\">\r\n");
              out.write("			     <input type=\"submit\" value=\"修改\">\r\n");
              out.write("			     <input type=\"hidden\" name=\"empno\" value=\"");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empVO.empno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("\">\r\n");
              out.write("			     <input type=\"hidden\" name=\"action\"	value=\"getOne_For_Update\"></FORM>\r\n");
              out.write("			</td>\r\n");
              out.write("			<td>\r\n");
              out.write("			  <FORM METHOD=\"post\" ACTION=\"");
              out.print(request.getContextPath());
              out.write("/emp/emp.do\" style=\"margin-bottom: 0px;\">\r\n");
              out.write("			     <input type=\"submit\" value=\"刪除\">\r\n");
              out.write("			     <input type=\"hidden\" name=\"empno\" value=\"");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empVO.empno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("\">\r\n");
              out.write("			     <input type=\"hidden\" name=\"action\" value=\"delete\"></FORM>\r\n");
              out.write("			</td>\r\n");
              out.write("		</tr>\r\n");
              out.write("	");
              int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
        } finally {
          _jspx_th_c_005fforEach_005f0.doFinally();
        }
        _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
        _jspx_th_c_005fforEach_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
      }
      out.write("\r\n");
      out.write("  </tbody>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
